#!/usr/bin/env bash

declare -x SOLDER_BROADCASTING_DRIVER
: "${SOLDER_BROADCASTING_DRIVER:="null"}"

declare -x SOLDER_BROADCASTING_PUSHER_KEY
: "${SOLDER_BROADCASTING_PUSHER_KEY:=""}"

declare -x SOLDER_BROADCASTING_PUSHER_SECRET
: "${SOLDER_BROADCASTING_PUSHER_SECRET:=""}"

declare -x SOLDER_BROADCASTING_PUSHER_APP_ID
: "${SOLDER_BROADCASTING_PUSHER_APP_ID:=""}"

declare -x SOLDER_BROADCASTING_PUSHER_CLUSTER
: "${SOLDER_BROADCASTING_PUSHER_CLUSTER:=""}"

declare -x SOLDER_BROADCASTING_ABLY_KEY
: "${SOLDER_BROADCASTING_ABLY_KEY:=""}"

declare -x SOLDER_BROADCASTING_REDIS_CONNECTION
: "${SOLDER_BROADCASTING_REDIS_CONNECTION:="default"}"
