#!/usr/bin/env bash

declare -x SOLDER_FILESYSTEM_DRIVER
: "${SOLDER_FILESYSTEM_DRIVER:="local"}"

declare -x SOLDER_FILESYSTEM_LOCAL_ROOT
: "${SOLDER_FILESYSTEM_LOCAL_ROOT:=""}"

declare -x SOLDER_FILESYSTEM_PUBLIC_ROOT
: "${SOLDER_FILESYSTEM_PUBLIC_ROOT:=""}"

declare -x SOLDER_FILESYSTEM_PUBLIC_URL
: "${SOLDER_FILESYSTEM_PUBLIC_URL:=""}"

declare -x SOLDER_FILESYSTEM_PUBLIC_VISIBILITY
: "${SOLDER_FILESYSTEM_PUBLIC_VISIBILITY:="public"}"

declare -x SOLDER_FILESYSTEM_S3_KEY
: "${SOLDER_FILESYSTEM_S3_KEY:="${AWS_ACCESS_KEY_ID}"}"

declare -x SOLDER_FILESYSTEM_S3_SECRET
: "${SOLDER_FILESYSTEM_S3_SECRET:="${AWS_SECRET_ACCESS_KEY}"}"

declare -x SOLDER_FILESYSTEM_S3_REGION
: "${SOLDER_FILESYSTEM_S3_REGION:="${AWS_DEFAULT_REGION}"}"

declare -x SOLDER_FILESYSTEM_S3_BUCKET
: "${SOLDER_FILESYSTEM_S3_BUCKET:=""}"

declare -x SOLDER_FILESYSTEM_S3_URL
: "${SOLDER_FILESYSTEM_S3_URL:=""}"

declare -x SOLDER_FILESYSTEM_S3_ENDPOINT
: "${SOLDER_FILESYSTEM_S3_ENDPOINT:=""}"

declare -x SOLDER_FILESYSTEM_S3_PATH_STYLE
: "${SOLDER_FILESYSTEM_S3_PATH_STYLE:="false"}"
