#!/usr/bin/env bash

declare -x SOLDER_SERVICES_MAILGUN_DOMAIN
: "${SOLDER_SERVICES_MAILGUN_DOMAIN:=""}"

declare -x SOLDER_SERVICES_MAILGUN_SECRET
: "${SOLDER_SERVICES_MAILGUN_SECRET:=""}"

declare -x SOLDER_SERVICES_MAILGUN_ENDPOINT
: "${SOLDER_SERVICES_MAILGUN_ENDPOINT:="api.mailgun.net"}"

declare -x SOLDER_SERVICES_POSTMARK_TOKEN
: "${SOLDER_SERVICES_POSTMARK_TOKEN:=""}"

declare -x SOLDER_SERVICES_SES_KEY
: "${SOLDER_SERVICES_SES_KEY:="${AWS_ACCESS_KEY_ID}"}"

declare -x SOLDER_SERVICES_SES_SECRET
: "${SOLDER_SERVICES_SES_SECRET:="${AWS_SECRET_ACCESS_KEY}"}"

declare -x SOLDER_SERVICES_SES_REGION
: "${SOLDER_SERVICES_SES_REGION:="${AWS_DEFAULT_REGION}"}"
