#!/usr/bin/env bash

declare -x SOLDER_HASHING_DRIVER
[[ -z "${SOLDER_HASHING_DRIVER}" ]] && SOLDER_HASHING_DRIVER="bcrypt"

declare -x SOLDER_HASHING_BCRYPT_ROUNDS
[[ -z "${SOLDER_HASHING_BCRYPT_ROUNDS}" ]] && SOLDER_HASHING_BCRYPT_ROUNDS="10"

declare -x SOLDER_HASHING_ARGON_MEMORY
[[ -z "${SOLDER_HASHING_ARGON_MEMORY}" ]] && SOLDER_HASHING_ARGON_MEMORY="65536"

declare -x SOLDER_HASHING_ARGON_THREADS
[[ -z "${SOLDER_HASHING_ARGON_THREADS}" ]] && SOLDER_HASHING_ARGON_THREADS="1"

declare -x SOLDER_HASHING_ARGON_TIME
[[ -z "${SOLDER_HASHING_ARGON_TIME}" ]] && SOLDER_HASHING_ARGON_TIME="4"

true
