#!/usr/bin/env bash

declare -x SOLDER_LOGGING_CHANNEL
: "${SOLDER_LOGGING_CHANNEL:="stack"}"

declare -x SOLDER_LOGGING_DEPRECATIONS_CHANNEL
: "${SOLDER_LOGGING_DEPRECATIONS_CHANNEL:="null"}"

declare -x SOLDER_LOGGING_STACK_CHANNELS
: "${SOLDER_LOGGING_STACK_CHANNELS:="single"}"

declare -x SOLDER_LOGGING_LEVEL
: "${SOLDER_LOGGING_LEVEL:="debug"}"

declare -x SOLDER_LOGGING_DAYS
: "${SOLDER_LOGGING_DAYS:="14"}"

declare -x SOLDER_LOGGING_SINGLE_PATH
: "${SOLDER_LOGGING_SINGLE_PATH:=""}"

declare -x SOLDER_LOGGING_DAILY_PATH
: "${SOLDER_LOGGING_DAILY_PATH:=""}"

declare -x SOLDER_LOGGING_EMERGENCY_PATH
: "${SOLDER_LOGGING_EMERGENCY_PATH:=""}"

declare -x SOLDER_LOGGING_SLACK_URL
: "${SOLDER_LOGGING_SLACK_URL:=""}"

declare -x SOLDER_LOGGING_SLACK_USERNAME
: "${SOLDER_LOGGING_SLACK_USERNAME:="Solder"}"

declare -x SOLDER_LOGGING_SLACK_EMOJI
: "${SOLDER_LOGGING_SLACK_EMOJI:=":boom:"}"

declare -x SOLDER_LOGGING_PAPERTRAIL_HANDLER
: "${SOLDER_LOGGING_PAPERTRAIL_HANDLER:=""}"

declare -x SOLDER_LOGGING_PAPERTRAIL_URL
: "${SOLDER_LOGGING_PAPERTRAIL_URL:=""}"

declare -x SOLDER_LOGGING_PAPERTRAIL_PORT
: "${SOLDER_LOGGING_PAPERTRAIL_PORT:=""}"

declare -x SOLDER_LOGGING_PAPERTRAIL_CONNECTION_STRING
: "${SOLDER_LOGGING_PAPERTRAIL_CONNECTION_STRING:=""}"

declare -x SOLDER_LOGGING_STDERR_FORMATTER
: "${SOLDER_LOGGING_STDERR_FORMATTER:=""}"
