#!/usr/bin/env bash

declare -x SOLDER_MAIL_DRIVER
: "${SOLDER_MAIL_DRIVER:="smtp"}"

declare -x SOLDER_MAIL_HOST
: "${SOLDER_MAIL_HOST:=""}"

declare -x SOLDER_MAIL_PORT
: "${SOLDER_MAIL_PORT:="587"}"

declare -x SOLDER_MAIL_ENCRYPTION
: "${SOLDER_MAIL_ENCRYPTION:="tls"}"

declare -x SOLDER_MAIL_USERNAME
: "${SOLDER_MAIL_USERNAME:=""}"

declare -x SOLDER_MAIL_PASSWORD
: "${SOLDER_MAIL_PASSWORD:=""}"

declare -x SOLDER_MAIL_SENDMAIL
: "${SOLDER_MAIL_SENDMAIL:="/usr/sbin/sendmail -t -i"}"

declare -x SOLDER_MAIL_LOG_CHANNEL
: "${SOLDER_MAIL_LOG_CHANNEL:=""}"

declare -x SOLDER_MAIL_FAILOVER_MAILERS
: "${SOLDER_MAIL_FAILOVER_MAILERS:="smtp,log"}"

declare -x SOLDER_MAIL_FROM_ADDRESS
: "${SOLDER_MAIL_FROM_ADDRESS:="solder@example.com"}"

declare -x SOLDER_MAIL_FROM_NAME
: "${SOLDER_MAIL_FROM_NAME:="Solder"}"

declare -x SOLDER_MAIL_MARKDOWN_THEME
: "${SOLDER_MAIL_MARKDOWN_THEME:="default"}"

declare -x SOLDER_MAIL_MARKDOWN_PATHS
: "${SOLDER_MAIL_MARKDOWN_PATHS:=""}"
