#!/usr/bin/env bash

declare -x SOLDER_SESSION_DRIVER
: "${SOLDER_SESSION_DRIVER:="file"}"

declare -x SOLDER_SESSION_LIFETIME
: "${SOLDER_SESSION_LIFETIME:="120"}"

declare -x SOLDER_SESSION_EXPIRE_ON_CLOSE
: "${SOLDER_SESSION_EXPIRE_ON_CLOSE:="false"}"

declare -x SOLDER_SESSION_ENCRYPT
: "${SOLDER_SESSION_ENCRYPT:="false"}"

declare -x SOLDER_SESSION_FILES
: "${SOLDER_SESSION_FILES:=""}"

declare -x SOLDER_SESSION_CONNECTION
: "${SOLDER_SESSION_CONNECTION:=""}"

declare -x SOLDER_SESSION_STORE
: "${SOLDER_SESSION_STORE:=""}"

declare -x SOLDER_SESSION_COOKIE
: "${SOLDER_SESSION_COOKIE:=""}"

declare -x SOLDER_SESSION_PATH
: "${SOLDER_SESSION_PATH:="/"}"

declare -x SOLDER_SESSION_DOMAIN
: "${SOLDER_SESSION_DOMAIN:=""}"

declare -x SOLDER_SESSION_SECURE_COOKIE
: "${SOLDER_SESSION_SECURE_COOKIE:=""}"

declare -x SOLDER_SESSION_HTTP_ONLY
: "${SOLDER_SESSION_HTTP_ONLY:="true"}"

declare -x SOLDER_SESSION_SAME_SITE
: "${SOLDER_SESSION_SAME_SITE:="lax"}"
