#!/bin/bash

declare -x SOLDER_APP_DEBUG
declare -x SOLDER_APP_URL
declare -x SOLDER_APP_TIMEZONE
declare -x SOLDER_APP_LOCALE
declare -x SOLDER_APP_CIPHER
declare -x SOLDER_APP_KEY
declare -x SOLDER_REDIS_HOST
declare -x SOLDER_REDIS_PORT
declare -x SOLDER_REDIS_DATABASE
declare -x SOLDER_REDIS_CLUSTER
declare -x SOLDER_MAIL_DRIVER
declare -x SOLDER_MAIL_HOST
declare -x SOLDER_MAIL_PORT
declare -x SOLDER_MAIL_ENCRYPTION
declare -x SOLDER_MAIL_USERNAME
declare -x SOLDER_MAIL_PASSWORD
declare -x SOLDER_MAIL_ADDRESS
declare -x SOLDER_MAIL_NAME
declare -x SOLDER_MAIL_SENDMAIL
declare -x SOLDER_REPO_LOCATION
declare -x SOLDER_MIRROR_URL
declare -x SOLDER_USE_S3
declare -x SOLDER_S3_ACCESS_KEY
declare -x SOLDER_S3_SECRET_KEY
declare -x SOLDER_S3_BUCKET
declare -x SOLDER_DB_TYPE

[[ -z "${SOLDER_APP_DEBUG}" ]] && SOLDER_APP_DEBUG="false"
[[ -z "${SOLDER_APP_URL}" ]] && SOLDER_APP_URL="http://localhost:8080"
[[ -z "${SOLDER_APP_TIMEZONE}" ]] && SOLDER_APP_TIMEZONE="UTC"
[[ -z "${SOLDER_APP_LOCALE}" ]] && SOLDER_APP_LOCALE="en"
[[ -z "${SOLDER_APP_CIPHER}" ]] && SOLDER_APP_CIPHER="MCRYPT_RIJNDAEL_128"
[[ -z "${SOLDER_REDIS_HOST}" ]] && SOLDER_REDIS_HOST="redis"
[[ -z "${SOLDER_REDIS_PORT}" ]] && SOLDER_REDIS_PORT="6379"
[[ -z "${SOLDER_REDIS_DATABASE}" ]] && SOLDER_REDIS_DATABASE="0"
[[ -z "${SOLDER_REDIS_CLUSTER}" ]] && SOLDER_REDIS_CLUSTER="false"
[[ -z "${SOLDER_MAIL_DRIVER}" ]] && SOLDER_MAIL_DRIVER="smtp"
[[ -z "${SOLDER_MAIL_HOST}" ]] && SOLDER_MAIL_HOST="smtp.mailgun.org"
[[ -z "${SOLDER_MAIL_PORT}" ]] && SOLDER_MAIL_PORT="587"
[[ -z "${SOLDER_MAIL_ENCRYPTION}" ]] && SOLDER_MAIL_ENCRYPTION="tls"
[[ -z "${SOLDER_MAIL_ADDRESS}" ]] && SOLDER_MAIL_ADDRESS="solder@localhost"
[[ -z "${SOLDER_MAIL_NAME}" ]] && SOLDER_MAIL_NAME="Solder"
[[ -z "${SOLDER_MAIL_SENDMAIL}" ]] && SOLDER_MAIL_SENDMAIL="/usr/sbin/sendmail -bs"
[[ -z "${SOLDER_USE_S3}" ]] && SOLDER_USE_S3="false"
[[ -z "${SOLDER_S3_BUCKET}" ]] && SOLDER_S3_BUCKET="solder"
[[ -z "${SOLDER_DB_TYPE}" ]] && SOLDER_DB_TYPE="mysql"

case "${SOLDER_DB_TYPE}" in
  "sqlite")
    declare -x SOLDER_DB_DATABASE
    declare -x SOLDER_DB_PREFIX

    [[ -z "${SOLDER_DB_DATABASE}" ]] && SOLDER_DB_DATABASE="/storage/database.sqlite3"
    ;;

  "mysql")
    declare -x SOLDER_DB_HOST
    declare -x SOLDER_DB_DATABASE
    declare -x SOLDER_DB_USERNAME
    declare -x SOLDER_DB_PASSWORD
    declare -x SOLDER_DB_PREFIX
    declare -x SOLDER_DB_CHARSET
    declare -x SOLDER_DB_COLLATION

    [[ -z "${SOLDER_DB_HOST}" ]] && SOLDER_DB_HOST="mysql"
    [[ -z "${SOLDER_DB_DATABASE}" ]] && SOLDER_DB_DATABASE="solder"
    [[ -z "${SOLDER_DB_USERNAME}" ]] && SOLDER_DB_USERNAME="root"
    [[ -z "${SOLDER_DB_PASSWORD}" ]] && SOLDER_DB_PASSWORD="root"
    [[ -z "${SOLDER_DB_CHARSET}" ]] && SOLDER_DB_CHARSET="utf8"
    [[ -z "${SOLDER_DB_COLLATION}" ]] && SOLDER_DB_COLLATION="utf8_general_ci"
    ;;

  "pgsql")
    declare -x SOLDER_DB_HOST
    declare -x SOLDER_DB_DATABASE
    declare -x SOLDER_DB_USERNAME
    declare -x SOLDER_DB_PASSWORD
    declare -x SOLDER_DB_PREFIX
    declare -x SOLDER_DB_CHARSET
    declare -x SOLDER_DB_SCHEMA

    [[ -z "${SOLDER_DB_HOST}" ]] && SOLDER_DB_HOST="postgres"
    [[ -z "${SOLDER_DB_DATABASE}" ]] && SOLDER_DB_DATABASE="solder"
    [[ -z "${SOLDER_DB_USERNAME}" ]] && SOLDER_DB_USERNAME="root"
    [[ -z "${SOLDER_DB_PASSWORD}" ]] && SOLDER_DB_PASSWORD="root"
    [[ -z "${SOLDER_DB_CHARSET}" ]] && SOLDER_DB_CHARSET="utf8"
    [[ -z "${SOLDER_DB_SCHEMA}" ]] && SOLDER_DB_SCHEMA="public"
    ;;
esac

if [ -z "${SOLDER_APP_KEY}" ]
then
  if [ -f /storage/secret ]
  then
    SOLDER_APP_KEY=$(cat /storage/secret | head -n1)
  else
    SOLDER_APP_KEY=$(date +%s | sha256sum | base64 | head -c 32 ; echo)
    echo "${SOLDER_APP_KEY}" > /storage/secret
  fi
fi
