FROM ghcr.io/dockhippie/php-apache:8.4-amd64@sha256:ae6a92cc508346dce6d3c339316d018de4bfcb5bf07b272b4646873b13c58cde

VOLUME ["/var/lib/solder"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add php${PHP_PACKAGE_VERSION}-bcmath@testing sqlite && \
  rm -rf /var/cache/apk/*

ENV PHP_COMPOSER_INSTALL=false

# renovate: datasource=github-releases depName=TechnicPack/TechnicSolder
ENV SOLDER_VERSION=0.7.16

# renovate: datasource=github-releases depName=aptible/supercronic
ENV SUPERCRONIC_VERSION=0.2.42

RUN curl -sSLo - https://github.com/TechnicPack/TechnicSolder/archive/refs/tags/v${SOLDER_VERSION}.tar.gz | tar -xzf - --strip 1 -C /srv/www && \
  cd /srv/www && \
  rm -f /srv/www/.env* && \
  composer config --no-plugins allow-plugins.php-http/discovery true && \
  composer install --no-dev --no-interaction && \
  chown -R apache:apache /srv/www && \
  curl -sSLo /usr/bin/supercronic https://github.com/aptible/supercronic/releases/download/v${SUPERCRONIC_VERSION}/supercronic-linux-amd64 && \
  chmod +x /usr/bin/supercronic

COPY ./overlay /

RUN find /etc/container.d /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/container* && \
  chmod +x /usr/bin/container* /etc/container.d/*.sh /etc/entrypoint.d/*.sh
