FROM ghcr.io/dockhippie/php-apache:8.4-arm@sha256:665b87307a20a09218957db87eb9a6ed9784bd5acf44b279c061a4b1296fe4c1

VOLUME ["/var/lib/solder"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add php${PHP_PACKAGE_VERSION}-bcmath@testing sqlite && \
  rm -rf /var/cache/apk/*

ENV PHP_COMPOSER_INSTALL=false

# renovate: datasource=github-releases depName=TechnicPack/TechnicSolder
ENV SOLDER_VERSION=0.7.16

# renovate: datasource=github-releases depName=aptible/supercronic
ENV SUPERCRONIC_VERSION=0.2.34

RUN curl -sSLo - https://github.com/TechnicPack/TechnicSolder/archive/refs/tags/v${SOLDER_VERSION}.tar.gz | tar -xzf - --strip 1 -C /srv/www && \
  cd /srv/www && \
  rm -f /srv/www/.env* && \
  composer config --no-plugins allow-plugins.php-http/discovery true && \
  composer install --no-dev --no-interaction && \
  chown -R apache:apache /srv/www && \
  curl -sSLo /usr/bin/supercronic https://github.com/aptible/supercronic/releases/download/v${SUPERCRONIC_VERSION}/supercronic-linux-arm && \
  chmod +x /usr/bin/supercronic

COPY ./overlay /
