#!/bin/bash

# declare -x DOLLAR="$"
# declare -x OWNCLOUD_IPADDRESS
# declare -x OWNCLOUD_DOMAIN
# declare -x OWNCLOUD_DB_TYPE
# declare -x OWNCLOUD_DB_NAME
# declare -x OWNCLOUD_DB_USERNAME
# declare -x OWNCLOUD_DB_PASSWORD
# declare -x OWNCLOUD_DB_HOST
# declare -x OWNCLOUD_DB_PREFIX
# declare -x OWNCLOUD_ADMIN_USERNAME
# declare -x OWNCLOUD_ADMIN_PASSWORD

# if [ -z "${OWNCLOUD_IPADDRESS}" ]
# then
#   OWNCLOUD_IPADDRESS=$(awk 'NR==1 {print $1}' /etc/hosts)
# fi

# if [ -z "${OWNCLOUD_DOMAIN}" ]
# then
#   OWNCLOUD_DOMAIN=${HOSTNAME}
# fi

# if [ -z "${OWNCLOUD_DB_TYPE}" ]
# then
#   OWNCLOUD_DB_TYPE=sqlite
# fi

# if [ -z "${OWNCLOUD_DB_NAME}" ]
# then
#   OWNCLOUD_DB_NAME=owncloud
# fi

# if [ -z "${OWNCLOUD_DB_USERNAME}" ]
# then
#   OWNCLOUD_DB_USERNAME=
# fi

# if [ -z "${OWNCLOUD_DB_PASSWORD}" ]
# then
#   OWNCLOUD_DB_PASSWORD=
# fi

# if [ -z "${OWNCLOUD_DB_HOST}" ]
# then
#   OWNCLOUD_DB_HOST=
# fi

# if [ -z "${OWNCLOUD_DB_PREFIX}" ]
# then
#   OWNCLOUD_DB_PREFIX=
# fi

# if [ -z "${OWNCLOUD_ADMIN_USERNAME}" ]
# then
#   OWNCLOUD_ADMIN_USERNAME=admin
# fi

# if [ -z "${OWNCLOUD_ADMIN_PASSWORD}" ]
# then
#   OWNCLOUD_ADMIN_PASSWORD=admin
# fi

# if [[ ! -f /app/config/domains.config.php ]]
# then
#   envsubst < /etc/templates/domains.config.php > /app/config/domains.config.php
#   chown apache:apache /app/config/domains.config.php
# fi

# if [[ ! -f /app/config/apps.config.php ]]
# then
#   cp /etc/templates/apps.config.php /app/config/apps.config.php
#   chown apache:apache /app/config/apps.config.php
# fi

# if [[ ! -f /app/config/logging.config.php ]]
# then
#   cp /etc/templates/logging.config.php /app/config/logging.config.php
#   chown apache:apache /app/config/logging.config.php
# fi

# if [[ ! -f /app/config/config.php ]]
# then
#   pushd /app > /dev/null
#   CMD="/usr/bin/php occ maintenance:install --no-interaction --data-dir /app/data"

#   [[ -n "${OWNCLOUD_DB_TYPE}" ]] && CMD="${CMD} --database ${OWNCLOUD_DB_TYPE}"
#   [[ -n "${OWNCLOUD_DB_NAME}" ]] && CMD="${CMD} --database-name ${OWNCLOUD_DB_NAME}"
#   [[ -n "${OWNCLOUD_DB_USERNAME}" ]] && CMD="${CMD} --database-user ${OWNCLOUD_DB_USERNAME}"
#   [[ -n "${OWNCLOUD_DB_PASSWORD}" ]] && CMD="${CMD} --database-pass ${OWNCLOUD_DB_PASSWORD}"
#   [[ -n "${OWNCLOUD_DB_HOST}" ]] && CMD="${CMD} --database-host ${OWNCLOUD_DB_HOST}"
#   [[ -n "${OWNCLOUD_DB_PREFIX}" ]] && CMD="${CMD} --database-table-prefix ${OWNCLOUD_DB_PREFIX}"
#   [[ -n "${OWNCLOUD_ADMIN_USERNAME}" ]] && CMD="${CMD} --admin-user ${OWNCLOUD_ADMIN_USERNAME}"
#   [[ -n "${OWNCLOUD_ADMIN_PASSWORD}" ]] && CMD="${CMD} --admin-pass ${OWNCLOUD_ADMIN_PASSWORD}"

#   echo "Installing with: ${CMD}"
#   su apache -c "${CMD}"

#   popd > /dev/null
# else
#   pushd /app > /dev/null
#   CMD="/usr/bin/php occ upgrade --skip-migration-test --no-interaction"

#   echo "Upgrading with: ${CMD}"
#   su apache -c "${CMD}"

#   popd > /dev/null
# fi

# pushd /app > /dev/null
# su apache -c "/usr/bin/php occ background:cron --no-interaction"
# popd > /dev/null
