#!/bin/bash

case "${SOLDER_DB_TYPE}" in
  "sqlite")
    if [ -z "${SOLDER_DB_DATABASE}" ]
    then
      echo >&2 "Error: You have to provide SOLDER_DB_DATABASE environment variable"
      s6-svc -t /etc/s6
      exit 1
    fi

    if [ ! -f "${SOLDER_DB_DATABASE}" ]
    then
      /usr/bin/gosu \
        caddy \
        /usr/bin/sqlite3 \
        ${SOLDER_DB_DATABASE} \
        ""
    fi
    ;;

  "mysql")
    if [ -z "${SOLDER_DB_USERNAME}" ]
    then
      echo >&2 "Error: You have to provide SOLDER_DB_USERNAME environment variable"
      s6-svc -t /etc/s6
      exit 1
    fi

    if [ -z "${SOLDER_DB_PASSWORD}" ]
    then
      echo >&2 "Error: You have to provide SOLDER_DB_PASSWORD environment variable"
      s6-svc -t /etc/s6
      exit 1
    fi
    ;;

  "pgsql")
    if [ -z "${SOLDER_DB_USERNAME}" ]
    then
      echo >&2 "Error: You have to provide SOLDER_DB_USERNAME environment variable"
      s6-svc -t /etc/s6
      exit 1
    fi

    if [ -z "${SOLDER_DB_PASSWORD}" ]
    then
      echo >&2 "Error: You have to provide SOLDER_DB_PASSWORD environment variable"
      s6-svc -t /etc/s6
      exit 1
    fi
    ;;
esac

if [ -z "${SOLDER_APP_KEY}" ]
then
  echo >&2 "Error: You have to provide SOLDER_APP_KEY environment variable"
  /bin/s6-svscanctl -t /etc/s6
  exit 1
fi

if [ -z "${SOLDER_APP_URL}" ]
then
  echo >&2 "Error: You have to provide SOLDER_APP_URL environment variable"
  /bin/s6-svscanctl -t /etc/s6
  exit 1
fi

if [ -z "${SOLDER_REPO_LOCATION}" ]
then
  echo >&2 "Error: You have to provide SOLDER_REPO_LOCATION environment variable"
  /bin/s6-svscanctl -t /etc/s6
  exit 1
fi

if [ -z "${SOLDER_MIRROR_URL}" ]
then
  echo >&2 "Error: You have to provide SOLDER_MIRROR_URL environment variable"
  /bin/s6-svscanctl -t /etc/s6
  exit 1
fi

/usr/bin/templater -d -p solder \
  -o /srv/www/app/config/database.php \
  /etc/templates/database.php.tmpl

/usr/bin/templater -d -p solder \
  -o /srv/www/app/config/app.php \
  /etc/templates/app.php.tmpl

/usr/bin/templater -d -p solder \
  -o /srv/www/app/config/mail.php \
  /etc/templates/mail.php.tmpl

/usr/bin/templater -d -p solder \
  -o /srv/www/app/config/solder.php \
  /etc/templates/solder.php.tmpl

pushd /srv/www > /dev/null
  /usr/bin/gosu \
    caddy \
    /usr/bin/php \
    artisan \
    clear-compiled -n -q

  /usr/bin/gosu \
    caddy \
    /usr/bin/php \
    artisan \
    optimize -n -q

  /usr/bin/gosu \
    caddy \
    /usr/bin/php \
    artisan \
    migrate:install -n -q

  /usr/bin/gosu \
    caddy \
    /usr/bin/php \
    artisan \
    migrate -n -q --force --seed
popd > /dev/null
